### ISSUE TITLE
Error when getting mp3

### ISSUE THREAD

**Issue by mgohin** [CodeStory/fluent-http#125]
I'm getting this error when trying to get a mp3 file with some browsers like IE10 or Chrome on Android. I don't have any problems with Chrome on OSX.
The file and folders all exist because I can read the file from my Chrome on OSX.

```
Error sending response
Unable to serve an error page
org.simpleframework.http.core.BodyEncoderException: Error sending response
	at org.simpleframework.http.core.FixedLengthEncoder.encode(FixedLengthEncoder.java:158)
	at org.simpleframework.http.core.ResponseEncoder.write(ResponseEncoder.java:197)
	at org.simpleframework.http.core.ResponseEncoder.write(ResponseEncoder.java:179)
	at org.simpleframework.http.core.ResponseBuffer.write(ResponseBuffer.java:210)
	at org.simpleframework.http.core.ResponseBuffer.write(ResponseBuffer.java:181)
	at org.simpleframework.http.core.ResponseBuffer.write(ResponseBuffer.java:160)
	at java.io.OutputStream.write(OutputStream.java:75)
	at net.codestory.http.payload.PayloadWriter.write(PayloadWriter.java:300)
	at net.codestory.http.payload.PayloadWriter.writeBytes(PayloadWriter.java:209)
	at net.codestory.http.payload.PayloadWriter.write(PayloadWriter.java:189)
	at net.codestory.http.payload.PayloadWriter.writeAndCloseSync(PayloadWriter.java:106)
	at net.codestory.http.payload.PayloadWriter.writeErrorPage(PayloadWriter.java:138)
	at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:156)
	at net.codestory.http.AbstractWebServer$$Lambda$36/1615873578.handle(Unknown Source)
	at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:73)
	at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
	at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
	at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.simpleframework.http.core.BodyEncoderException: Response content complete
	at org.simpleframework.http.core.FixedLengthEncoder.encode(FixedLengthEncoder.java:147)
	... 20 more
```

In my `Application.java` :

    [...]
    .bind("/files", applicationConfiguration.getFilesDirectory().toFile()) //binding to FS folder

Fluent : 2.98

Let me know if you need more infos ;)

**Comment by dgageot** [comment]
Did you sort out this problem?

**Comment by mgohin** [comment]
Did not remember the fix well, you fixed bad header and we changed the way to get files (we now bind à static files folder to an url so we access the file directly)
